const facts = [
  "Wordle was created by Josh Wardle, a software engineer from Brooklyn",
  "The game was initially created for Josh Wardle's partner, Palak Shah",
  "Wordle launched publicly in October 2021",
  "The New York Times purchased Wordle in January 2022 for an undisclosed seven-figure sum",
  "Players get exactly 6 attempts to guess the 5-letter word",
  "There is only one puzzle per day",
  "The game uses a color-coding system: green for correct letters in correct positions",
  "Yellow indicates correct letters in wrong positions",
  "Gray means the letter is not in the word at all",
  "Wordle became a viral sensation on Twitter in late 2021",
  "The game's popularity exploded after the colored emoji sharing feature was added",
  "Wordle has no ads or monetization in its original form",
  "The game is entirely browser-based and requires no download",
  "Josh Wardle previously worked at Reddit",
  "The name 'Wordle' is a play on Josh Wardle's surname",
  "Wordle uses a curated list of approximately 2,300 possible answers",
  "The game also has a larger list of about 13,000 valid guesses",
  "Common starting words include ADIEU, AUDIO, and RAISE",
  "The most common letters in English (ETAOIN) appear frequently in Wordle solutions",
  "Wordle solutions never include proper nouns",
  "Plural words ending in S are generally not used as solutions",
  "The game maintains the same word for all players on the same day worldwide",
  "Wordle resets at midnight in your local timezone",
  "The original Wordle had no dark mode initially",
  "Hard mode requires players to use revealed hints in subsequent guesses",
  "Colorblind accessibility features were added after community feedback",
  "The game tracks your statistics including games played and win percentage",
  "Your longest win streak is also tracked",
  "Wordle statistics are stored locally in your browser",
  "The game has inspired hundreds of variations and clones",
  "Absurdle is a Wordle variant that tries to avoid giving you the answer",
  "Worldle is a geography-based variant using country shapes",
  "Heardle was a music-based variant using song clips",
  "Nerdle applies the Wordle format to mathematical equations",
  "The optimal starting word is debated among players and mathematicians",
  "Some players prefer vowel-heavy starting words",
  "Others prefer consonant-heavy words with common letters",
  "The word SLATE has been calculated as statistically optimal by some analyses",
  "CRANE is another frequently recommended starting word",
  "The worst possible Wordle score is failing to guess in 6 tries",
  "Getting the word in 1 guess is extremely rare and largely luck-based",
  "The average Wordle score for experienced players is around 4 guesses",
  "Words with double letters can be particularly challenging",
  "The game doesn't indicate when letters appear multiple times",
  "ABBEY was one of the more controversial solutions due to double letters",
  "Some solutions have caused community debate about word obscurity",
  "The New York Times has occasionally changed solutions they deemed too difficult",
  "FETUS was changed to a different word due to its sensitive nature",
  "The game originally had no sharing feature",
  "The emoji sharing grid was added to prevent spoilers while allowing sharing",
  "Wordle sharing posts don't reveal the actual word",
  "The game helped boost New York Times Games subscription numbers",
  "Wordle is now part of the New York Times Games bundle",
  "The original standalone website still redirects to NYT",
  "Josh Wardle has expressed mixed feelings about the game's massive success",
  "The game was inspired by the TV game show Lingo",
  "Mastermind, the code-breaking game, also influenced Wordle's design",
  "The five-letter word format was chosen for optimal difficulty",
  "Four-letter words were deemed too easy during development",
  "Six-letter words were considered too difficult for daily play",
  "The game's minimalist design was intentional",
  "Wordle has been translated into multiple languages",
  "Different language versions use words appropriate to that language",
  "The game works on all modern web browsers",
  "Mobile browsers display Wordle in a responsive format",
  "No special keyboard is required - standard QWERTY works fine",
  "The on-screen keyboard shows which letters you've used",
  "Used letters are color-coded on the virtual keyboard too",
  "Wordle has been credited with improving people's vocabulary",
  "Teachers have incorporated Wordle into English language lessons",
  "The game has sparked interest in word games among younger generations",
  "Wordle parties and group solving sessions became popular",
  "Some families make Wordle solving a daily ritual",
  "The game has been featured in major news outlets worldwide",
  "Academic papers have been written analyzing Wordle strategies",
  "Mathematicians have calculated optimal solving approaches",
  "Information theory has been applied to Wordle strategy",
  "The game demonstrates principles of entropy in information theory",
  "Wordle has been used to teach probability and statistics",
  "Some players have created elaborate spreadsheets to track patterns",
  "The game influenced baby naming trends briefly in 2022",
  "Wordle-themed merchandise became popular on various platforms",
  "Board game versions of Wordle have been created",
  "The game has been referenced in popular culture and TV shows",
  "Celebrity Wordle scores have been shared on social media",
  "The game created a shared cultural experience during the pandemic",
  "Wordle helped people maintain social connections through daily sharing",
  "The simple format made it accessible to players of all ages",
  "Grandparents and grandchildren often share their daily results",
  "The game has been praised for its lack of addictive mechanics",
  "No notifications or constant prompts to play exist",
  "The one-puzzle-per-day limit was a deliberate design choice",
  "This constraint helps prevent excessive screen time",
  "Wordle has influenced game design philosophy in the mobile gaming industry",
  "The game proves that simple concepts can still go viral",
  "Josh Wardle has remained relatively private despite the game's success",
  "The sale to New York Times allowed Wardle to focus on other projects",
  "Wordle's success led to increased interest in other word games",
  "Crossword puzzle popularity saw a boost following Wordle's success",
  "The game has been used in cognitive research studies",
  "Wordle performance has been studied in relation to vocabulary size",
  "The game demonstrates how constraints can enhance creativity",
  "Players often develop personal rituals around their daily Wordle attempt",
  "Some players solve it immediately upon waking up",
  "Others save it for their coffee break or commute",
  "The game has been integrated into some workplace cultures",
  "Teams sometimes compare scores as a daily icebreaker",
  "Wordle has inspired corporate team-building activities",
  "The game's success showed the power of organic social media growth",
  "No traditional advertising was used to promote Wordle initially",
  "Word-of-mouth and social sharing drove its explosive growth",
  "The game peaked at millions of daily players within months",
  "Server capacity became an issue during peak popularity periods",
  "The New York Times had to scale infrastructure to handle traffic",
  "Wordle has been blocked by some workplace internet filters",
  "This led to discussions about productivity and brief mental breaks",
  "The game has been used as a conversation starter in social settings",
  "Dating app profiles sometimes mention Wordle scores",
  "The game created a new form of daily social currency",
  "Sharing your score became a way to participate in a global community",
  "Bad Wordle days became a shared source of commiseration",
  "Exceptionally good scores became bragging rights",
  "The game has been analyzed for its psychological appeal",
  "The dopamine hit from solving the puzzle keeps players returning",
  "The fear of missing out (FOMO) encourages daily participation",
  "Wordle has been compared to other daily ritual activities",
  "Like crosswords, it became part of many people's morning routines",
  "The game has inspired academic courses on viral phenomena",
  "Business schools use Wordle as a case study in organic growth",
  "The game has been featured in linguistics research",
  "Letter frequency analysis has been applied to Wordle strategy",
  "The game has helped some people improve their spelling",
  "ESL students have used Wordle to practice English vocabulary",
  "The game has been adapted for educational purposes in schools",
  "Some teachers create classroom Wordle competitions",
  "The game has been used to teach computer science concepts",
  "Algorithm design can be demonstrated through Wordle solving strategies",
  "The game has inspired coding challenges and programming exercises",
  "GitHub repositories contain numerous Wordle solvers and analyzers",
  "Machine learning has been applied to optimize Wordle strategies",
  "AI systems have been trained to solve Wordle efficiently",
  "The game has been reverse-engineered by curious programmers",
  "Open-source clones have been created for educational purposes",
  "The game's source code has been studied for its elegant simplicity",
  "Wordle has influenced web development practices",
  "Its clean interface design has been emulated by other games",
  "The game demonstrates effective use of local storage in browsers",
  "Progressive Web App (PWA) principles are exemplified in Wordle",
  "The game works offline once initially loaded",
  "No user accounts or registration are required to play",
  "Privacy-conscious design choices have been praised",
  "The game doesn't track users or collect personal data extensively",
  "Wordle has been used to discuss digital privacy rights",
  "The transition to New York Times raised some privacy concerns",
  "Some players preferred the original independent version",
  "The game has been featured in discussions about platform ownership",
  "Independent creators versus corporate ownership debates arose",
  "Wordle has influenced discussions about monetizing viral content",
  "The creator's decision to sell sparked conversations about sellout culture",
  "The game has been used to teach lessons about sudden success",
  "Overnight viral success stories became more relatable through Wordle",
  "The game has inspired entrepreneurs to create simple, addictive products",
  "Minimalist game design became more popular after Wordle's success",
  "The game proved that complex graphics aren't necessary for engagement",
  "Wordle has been studied for its perfect difficulty curve",
  "The learning curve allows new players to improve gradually",
  "Expert players still find the daily challenge engaging",
  "The game balances accessibility with sufficient challenge",
  "Wordle has been praised for its inclusive design",
  "No special gaming skills or reflexes are required",
  "The turn-based nature accommodates different playing speeds",
  "Accessibility features support players with various needs",
  "The game has been translated for speakers of different languages",
  "Cultural adaptations consider local vocabulary preferences",
  "Some versions use different word lengths for different languages",
  "The game has inspired similar formats for other subjects",
  "Math, geography, and science versions have been created",
  "The Wordle format has been applied to movie titles and song names",
  "Food-themed versions use ingredient names and cooking terms",
  "Sports versions incorporate team names and athletic terminology",
  "The game has been used for brand marketing by various companies",
  "Custom corporate versions have been created for team building",
  "The format has been adapted for educational content delivery",
  "Wordle has influenced the broader casual gaming market",
  "Publishers have sought to replicate its viral success formula",
  "The game has been studied for its optimal engagement patterns",
  "Daily puzzle games saw increased popularity after Wordle",
  "The concept of artificial scarcity became more widely discussed",
  "Wordle has been featured in museum exhibitions about digital culture",
  "The game represents a moment in internet history",
  "It captured the collective attention during a specific cultural period",
  "Wordle has been preserved in digital archives for future study",
  "The game's social impact has been documented by researchers",
  "Wordle has been used to study viral content propagation",
  "Social network analysis has been applied to its sharing patterns",
  "The game demonstrates how simple concepts can unite global audiences",
  "Cultural differences in gameplay have been observed and studied",
  "Wordle has contributed to discussions about digital wellbeing",
  "Its restrained design philosophy contrasts with addictive gaming practices",
  "The game has been held up as an example of ethical game design",
  "Player-first design principles are exemplified in Wordle's structure",
  "The game has influenced policy discussions about screen time",
  "Healthy gaming habits have been promoted using Wordle as an example",
  "The game has been used in therapy and counseling contexts",
  "Cognitive behavioral therapy has incorporated Wordle-like activities",
  "The game provides a sense of daily accomplishment for many players",
  "Wordle has been used to establish routine for people with depression",
  "The social sharing aspect helps combat isolation",
  "The game has been studied for its mental health benefits",
  "Brief cognitive challenges like Wordle may help maintain mental acuity",
  "The game has been used in elderly care facilities",
  "Intergenerational play has been facilitated through Wordle",
  "The game has inspired family traditions and bonding activities",
  "Wordle tournaments have been organized in various communities",
  "Local competitions have brought people together around the game",
  "The game has been featured in charity fundraising events",
  "Wordle-themed parties and social gatherings have become popular",
  "The game has created new social rituals in the digital age",
  "Daily score sharing has become a form of social currency",
  "Wordle has influenced how people think about daily digital habits",
  "The game has been used to teach mindfulness and present-moment awareness",
  "Its daily constraint encourages players to be fully present",
  "Wordle has been incorporated into meditation and wellness practices",
  "The game represents a successful balance between challenge and relaxation",
  "Wordle continues to maintain a dedicated player base years after its peak",
  "The game's longevity demonstrates the power of well-designed constraints",
  "New players continue to discover and enjoy Wordle regularly",
  "The game has become a permanent part of internet culture",
  "Wordle's influence on game design continues to be felt across the industry"
]

export function getRandomFact() {
  const rand = Math.round(Math.random() * 200)
  return facts[rand]
}
